# Generated by Django 2.1.4 on 2018-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='admin', max_length=50, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
